### PR TITLE
When update fails, retry an overwrite

### LINKED ISSUE #37: Certain edits can result in invalid strategic patches
Certain edits, e.g. `spec.containers[0].ports.containerPort`, to deployments can cause an infinite loop as an operator attempts to reconcile by applying a manifest, e.g.
```
$ kubectl edit deploy -n knative-serving autoscaler
FROM
        ports:
        - containerPort: 9090
          name: metrics
          protocol: TCP
TO
        ports:
        - containerPort: 9091
          name: metrics
          protocol: TCP
```
The `knative-serving-operator` then produces the following "Duplicate value" error.
```
{"level":"error","ts":"2020-03-19T07:31:22.663Z","logger":"serving-operator.knativeserving-controller","caller":"controller/controller.go:409","msg":"Reconcile error","commit":"36ecf1b","knative.dev/controller":"knativeserving-controller","error":"Deployment.apps \"autoscaler\" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: \"metrics\"","stacktrace":"knative.dev/serving-operator/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\t/go/src/knative.dev/serving-operator/vendor/knative.dev/pkg/controller/controller.go:409\nknative.dev/serving-operator/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/go/src/knative.dev/serving-operator/vendor/knative.dev/pkg/controller/controller.go:395\nknative.dev/serving-operator/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\t/go/src/knative.dev/serving-operator/vendor/knative.dev/pkg/controller/controller.go:343"}
```
And the autoscaler's pod is still 9091. (We expect 9090).

Interesting to note that `kubectl apply` won't cause the error, only `kubectl edit`, since that causes the `last-applied` annotation to be out of sync.

This is related to other upstream issues in which applying a strategic patch yields to dupe value errors, e.g. kubernetes/kubernetes#78266 kubernetes/kubernetes#59119 kubernetes/kubernetes#62366. These are among the many reasons "server-side apply" is anxiously awaited by all.

### PR DESCRIPTION
**Pull request by jcrossley3**
Fixes #37 

This involves overlaying the manifest fields onto the current
resource, which might contain server-provided, immutable fields absent
from the manifest, e.g. a service's clusterIP or a creationTimestamp.

We take a conservative approach to overlaying objects with entirely
different structures, as might be the case when updating a new
release. This may still error, but there's not a lot we can do other
than delete/create. But I'd prefer the user to make that call.

### CODE REVIEW

File: manifestival.go [hunk 1]
```diff
@@ -103,20 +104,26 @@ func (m Manifest) apply(spec *unstructured.Unstructured, opts ...ApplyOption) er
...
+			}
 			m.log.Info("Merging", "diff", diff)
 			if err := diff.Merge(current); err != nil {
 				return err
 			}
-			return m.update(current, lastApplied(spec), opts...)
+			err = m.update(current, lastApplied(spec), opts...)
+			if err == nil {
+				return nil
+			}
```
Comment (nak3) [inline manifestival.go]: I wonder that it is better to filter the error type (like duplicated value error only), but it is not possible?

Comment (jcrossley3) [reply manifestival.go]: It is possible, sure. I can recognize any field error by its type, e.g. https://github.com/kubernetes/apimachinery/blob/kubernetes-1.16.0/pkg/util/validation/field/errors.go#L103

I figured any error is worth a retry, but I could see how retrying a network error would be useless. Do you think maybe only retry field/Errors? https://github.com/kubernetes/apimachinery/blob/kubernetes-1.16.0/pkg/util/validation/field/errors.go#L29-L36

Comment (nak3) [reply manifestival.go]: Great. Yes, I thought that network error is useless. So only retry field/Errors would be better, I think.

Comment (jcrossley3) [reply manifestival.go]: Cool. Done. We only retry for validation errors now. This cleaned up the logic quite a bit, and the `Overwrite` option now works like the `kubectl apply --overwrite` option, which also defaults to true.

Thanks for the feedback!
